# Generated by Django 4.1.7 on 2023-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('测试代码', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('测试名称', models.CharField(db_column='item', max_length=255)),
                ('分值', models.FloatField(blank=True, db_column='score', null=True)),
                ('multi', models.IntegerField(blank=True, null=True)),
                ('类别', models.CharField(blank=True, db_column='class0', max_length=255, null=True)),
                ('科室', models.CharField(blank=True, db_column='department', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scores',
                'managed': False,
            },
        ),
    ]
