# Generated by Django 5.0.1 on 2025-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('pri', models.AutoField(db_column='pri', primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, db_column='点位', max_length=255, null=True)),
                ('acq_date', models.CharField(blank=True, db_column='日期', max_length=255, null=True)),
                ('analylize', models.CharField(blank=True, db_column='分析员', max_length=255, null=True)),
                ('n1', models.IntegerField(blank=True, db_column='N1', null=True)),
                ('n2', models.IntegerField(blank=True, db_column='N2', null=True)),
                ('n3', models.IntegerField(blank=True, db_column='N3', null=True)),
                ('nall', models.IntegerField(blank=True, db_column='N总', null=True)),
                ('lamaxpb', models.FloatField(blank=True, db_column='Lamaxpb', null=True)),
                ('lwecpn', models.FloatField(blank=True, db_column='Lwecpn', null=True)),
                ('n1_20', models.IntegerField(blank=True, db_column='N1_20', null=True)),
                ('n2_20', models.IntegerField(blank=True, db_column='N2_20', null=True)),
                ('n3_20', models.IntegerField(blank=True, db_column='N3_20', null=True)),
                ('nall_20', models.IntegerField(blank=True, db_column='N总_20', null=True)),
                ('lamaxpb_20', models.FloatField(blank=True, db_column='Lamaxpb_20', null=True)),
                ('lwecpn_20', models.FloatField(blank=True, db_column='Lwecpn_20', null=True)),
                ('bg', models.FloatField(blank=True, db_column='背景', null=True)),
                ('cal_date', models.DateTimeField(blank=True, db_column='记录时间', null=True)),
            ],
            options={
                'db_table': '机场_day_精密_2023',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filein', models.CharField(max_length=255, null=True)),
                ('fileout', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('appname', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
