# Generated by Django 4.2 on 2023-11-09 01:22

from django.db import migrations, models
import seui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to=seui.models.uploade_to)),
                ('fileorgname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('filein', models.CharField(max_length=255, null=True)),
                ('fileout', models.CharField(max_length=255, null=True)),
                ('fileout_f', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('appname', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
