# Generated by Django 4.1.7 on 2023-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('filein', models.CharField(max_length=255)),
                ('fileout', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('appname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
