# Generated by Django 4.1.7 on 2023-04-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
