# Generated by Django 5.0.1 on 2026-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportNew',
            fields=[
                ('pri', models.AutoField(db_column='pri', primary_key=True, serialize=False)),
                ('point', models.CharField(blank=True, db_column='点位', max_length=255, null=True)),
                ('date', models.CharField(blank=True, db_column='日期', max_length=255, null=True)),
                ('ldn', models.FloatField(blank=True, db_column='Ldn', null=True)),
                ('nd_valid', models.IntegerField(blank=True, db_column='Nd_有效', null=True)),
                ('nn_valid', models.IntegerField(blank=True, db_column='Nn_有效', null=True)),
                ('nd_total', models.IntegerField(blank=True, db_column='Nd_总', null=True)),
                ('nn_total', models.IntegerField(blank=True, db_column='Nn_总', null=True)),
                ('is_valid', models.SmallIntegerField(blank=True, db_column='是否有效', null=True)),
                ('record_time', models.DateTimeField(blank=True, db_column='记录时间', null=True)),
            ],
            options={
                'db_table': '机场_新标准计算',
                'managed': False,
            },
        ),
    ]
