# Generated by Django 5.0.1 on 2024-04-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0002_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('pri', models.AutoField(db_column='pri', primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, db_column='点位', max_length=255, null=True)),
                ('acq_date', models.CharField(blank=True, db_column='日期', max_length=255, null=True)),
                ('analylize', models.CharField(blank=True, db_column='分析员', max_length=255, null=True)),
                ('n1', models.IntegerField(blank=True, db_column='N1', null=True)),
                ('n2', models.IntegerField(blank=True, db_column='N2', null=True)),
                ('n3', models.IntegerField(blank=True, db_column='N3', null=True)),
                ('nall', models.IntegerField(blank=True, db_column='N总', null=True)),
                ('lamaxpb', models.FloatField(blank=True, db_column='Lamaxpb', null=True)),
                ('lwecpn', models.FloatField(blank=True, db_column='Lwecpn', null=True)),
                ('bg', models.FloatField(blank=True, db_column='背景', null=True)),
                ('cal_date', models.DateTimeField(blank=True, db_column='记录时间', null=True)),
            ],
            options={
                'db_table': '机场_day_精密_2023',
                'managed': False,
            },
        ),
    ]
