# Generated by Django 5.0.1 on 2025-02-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0003_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='fileout_f',
        ),
    ]
