# Generated by Django 4.1.7 on 2023-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0004_alter_records_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
