# Generated by Django 4.1.7 on 2023-04-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0006_alter_records_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='appname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='filein',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='fileout',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
