# Generated by Django 4.1.7 on 2023-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0007_alter_records_appname_alter_records_filein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='fileout_f',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
