# Generated by Django 4.2 on 2023-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0009_modelwithfilefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
