# Generated by Django 4.2 on 2023-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0010_alter_modelwithfilefield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
