# Generated by Django 4.2 on 2023-04-26 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0011_alter_modelwithfilefield_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithfilefield',
            name='fileorgname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
