# Generated by Django 4.2 on 2023-04-26 08:07

from django.db import migrations, models
import seui.models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0012_modelwithfilefield_fileorgname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelwithfilefield',
            old_name='title',
            new_name='appname',
        ),
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='file',
            field=models.FileField(upload_to=seui.models.uploade_to),
        ),
    ]
