# Generated by Django 4.2 on 2023-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seui', '0013_rename_title_modelwithfilefield_appname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indextxt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frame', models.IntegerField()),
                ('txt', models.TextField(null=True)),
            ],
        ),
    ]
